version: '3.8'

services:
  web:
    build: 
      context: ./comments-api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./comments-api:/app
    depends_on:
      - db
    environment:
      - FLASK_APP=app/routes.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_DEBUG=1
      - PYTHONPATH=/app
    command: >
      sh -c "sleep 5 && flask run"

  db:
    image: postgres:13-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: comments_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: