apiVersion: apps/v1
kind: Deployment
metadata:
  name: comments-api-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comments-api
  template:
    metadata:
      labels:
        app: comments-api
    spec:
      containers:
        - name: comments-api
          image: $IMAGE_URL
          ports:
            - containerPort: 5000
          envFrom:
            - secretRef:
                name: comments-api-db-secret
          # env:
          #   - name: OTEL_EXPORTER_OTLP_ENDPOINT
          #     value: "http://otel-collector:4317"
          #   - name: OTEL_EXPORTER_OTLP_INSECURE
          #     value: "true"