apiVersion: apps/v1
kind: Deployment
metadata:
  name: comments-api-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comments-api
  template:
    metadata:
      labels:
        app: comments-api
    spec:
      containers:
        - name: comments-api
          image: 890675146779.dkr.ecr.us-east-1.amazonaws.com/comments-api-dev/comments-api-dev:latest
          ports:
            - containerPort: 8000